name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    strategy:
      matrix:
        arduino-platform: ["esp32:esp32"]

        include:
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      - name: Install Platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }} --config-file arduino-cli-config.yaml

      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn ${{ matrix.fqbn }} "basic" --verbose
